backend:
  name: git-gateway
  branch: main  # Asegúrate de que esta sea tu rama principal

media_folder: "static/img"  # Donde se almacenarán los archivos multimedia
public_folder: "/img"       # Ruta pública para los archivos multimedia

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"  # Aquí se encuentran tus archivos markdown
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
